openapi: 3.0.0
info:
  title: Calendar Orchestrator
  description: The Orchestrator component for the Solid Calendar (aka Knoodle).
  version: "0.1"
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /:
    get:
      summary: Server running indicator
      description: Returns a dummy information indicating the server is running
      responses:
        '200':    # status code
          description: A welcome message
          content:
            text/plain; charset=utf-8:
              schema: 
                type: string
  /user:
    get:
      summary: Returns user information.
      parameters:
        - in: query
          name: webid
          schema:
            type: string
          required: true
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  user:
                    type: string
                  ics:
                    type: string
        '500':
          description: Error message
    post:
      summary: Register or update a user information
      requestBody:
        description: |
          User information in different combinations:
          
          register: webid [+ issuer] + password + email;
          
          update calendar URL: webid + cal_url;
          
          update availability: webid [+ issuer];
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                webid:
                  type: string
                issuer:
                  type: string
                email:
                  type: string
                password:
                  type: string
                cal_url:
                  type: string
              required:
                - webid
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request (e.g. missing fields)
        '500':
          description: Error in executing request
    delete:
      summary: Delete a registered user
      parameters:
        - in: query
          name: webid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Success
        '500':
          description: Error
  /status:
    get:
      summary: Update all users' calendar data
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    webid:
                      type: string
